available_text_models: ["gpt-5-mini-2025-08-07"]

info:
  gpt-5-mini-2025-08-07:
    type: chat_completion
    name: GPT-5 Mini
    description: GPT-5 Mini is a faster and more cost-efficient version of GPT-5. It is designed for well-defined tasks and offers reduced latency.

    price_per_1000_input_tokens: 0.00025
    price_per_1000_output_tokens: 0.002

    scores:
      smart: 4
      fast: 5
      cheap: 5

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
